Return-Path: <linux-nilfs-owner@vger.kernel.org>
X-Original-To: lists+linux-nilfs@lfdr.de
Delivered-To: lists+linux-nilfs@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 779C67DDF15
	for <lists+linux-nilfs@lfdr.de>; Wed,  1 Nov 2023 11:11:35 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S233728AbjKAKLf (ORCPT <rfc822;lists+linux-nilfs@lfdr.de>);
        Wed, 1 Nov 2023 06:11:35 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:46116 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S231719AbjKAKLf (ORCPT
        <rfc822;linux-nilfs@vger.kernel.org>); Wed, 1 Nov 2023 06:11:35 -0400
Received: from mail-oi1-f198.google.com (mail-oi1-f198.google.com [209.85.167.198])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id EA32BF4
        for <linux-nilfs@vger.kernel.org>; Wed,  1 Nov 2023 03:11:28 -0700 (PDT)
Received: by mail-oi1-f198.google.com with SMTP id 5614622812f47-3b3ebbbdb1aso10255802b6e.2
        for <linux-nilfs@vger.kernel.org>; Wed, 01 Nov 2023 03:11:28 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1698833488; x=1699438288;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=bXahSEUy+14xsn/d7aszM5fHvVZhAbvct7hqKP00aRo=;
        b=aDAH71Cg3KgSnqTPRNNQZbYoXWjxryRyFuqc/jyRNC/aKpvosKNxoJHln0V7GsMqJg
         fxevJl+Vi5mtNNZ/0GWtxk9GsZrvG9FPL27b5T8MqyhIB2rlviVZUnZItkPLmXsmzDgo
         NzghZwagdtowvI9a97usUkYRnQeYPG3/86KkIUdpib3fSSx3qOLm8AN3UadItP110Bqf
         wE0zAzU9LtveJY5CVKVgbz4NUJ3OPoq3xfJFwWD11LFGnz72Rh6iefn0XpV9CyexEYXM
         m/TIU1i5pRKTC9RgDWJpp4tHOICUJw40aeP6S69F4I8qYH+2Op1eV4wYS3Q3i96kDM4S
         /r1Q==
X-Gm-Message-State: AOJu0YxaErKKW1LeuPpyRo867e5wuZw+oqJyZT3yEQnL0Z9ucJOcFDba
        JSmGVhEjVvaGSV56DDRiOD3mb1jrtN/WbhCBF6kKR2P5lLGb
X-Google-Smtp-Source: AGHT+IHoUKW4bJUZ+erPsgzbUz4MYK9ApwlDolBOgA5uUtcaQW9W9XQTqwf1JwXc/sUY4YarLT7VQ2PSP0V0yntlF9W/7m+rcUJx
MIME-Version: 1.0
X-Received: by 2002:a05:6808:f0b:b0:3ae:532c:e93a with SMTP id
 m11-20020a0568080f0b00b003ae532ce93amr5515798oiw.11.1698833488314; Wed, 01
 Nov 2023 03:11:28 -0700 (PDT)
Date:   Wed, 01 Nov 2023 03:11:28 -0700
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <0000000000009a89f30609147ef3@google.com>
Subject: [syzbot] Monthly nilfs report (Oct 2023)
From:   syzbot <syzbot+listfef7805b7a90b5da7492@syzkaller.appspotmail.com>
To:     konishi.ryusuke@gmail.com, linux-fsdevel@vger.kernel.org,
        linux-kernel@vger.kernel.org, linux-nilfs@vger.kernel.org,
        syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"
X-Spam-Status: No, score=-1.7 required=5.0 tests=BAYES_00,FROM_LOCAL_HEX,
        HEADER_FROM_DIFFERENT_DOMAINS,RCVD_IN_DNSWL_BLOCKED,RCVD_IN_MSPIKE_H2,
        SPF_HELO_NONE,SPF_PASS,T_SCC_BODY_TEXT_LINE,URIBL_BLOCKED autolearn=no
        autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-nilfs.vger.kernel.org>
X-Mailing-List: linux-nilfs@vger.kernel.org

Hello nilfs maintainers/developers,

This is a 31-day syzbot report for the nilfs subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/nilfs

During the period, 0 new issues were detected and 0 were fixed.
In total, 6 issues are still open and 36 have been fixed so far.

Some of the still happening issues:

Ref Crashes Repro Title
<1> 366     Yes   kernel BUG at fs/buffer.c:LINE!
                  https://syzkaller.appspot.com/bug?extid=cfed5b56649bddf80d6e
<2> 337     Yes   WARNING in nilfs_sufile_set_segment_usage
                  https://syzkaller.appspot.com/bug?extid=14e9f834f6ddecece094
<3> 224     No    INFO: task hung in path_openat (7)
                  https://syzkaller.appspot.com/bug?extid=950a0cdaa2fdd14f5bdc
<4> 105     Yes   INFO: task hung in nilfs_detach_log_writer
                  https://syzkaller.appspot.com/bug?extid=e3973c409251e136fdd0
<5> 6       Yes   kernel BUG in end_buffer_async_write
                  https://syzkaller.appspot.com/bug?extid=5c04210f7c7f897c1e7f

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.

To disable reminders for individual bugs, reply with the following command:
#syz set <Ref> no-reminders

To change bug's subsystems, reply with:
#syz set <Ref> subsystems: new-subsystem

You may send multiple commands in a single email message.
