Return-Path: <linux-nilfs+bounces-55-lists+linux-nilfs=lfdr.de@vger.kernel.org>
X-Original-To: lists+linux-nilfs@lfdr.de
Delivered-To: lists+linux-nilfs@lfdr.de
Received: from am.mirrors.kernel.org (am.mirrors.kernel.org [147.75.80.249])
	by mail.lfdr.de (Postfix) with ESMTPS id A7E54801D5A
	for <lists+linux-nilfs@lfdr.de>; Sat,  2 Dec 2023 15:45:30 +0100 (CET)
Received: from smtp.subspace.kernel.org (wormhole.subspace.kernel.org [52.25.139.140])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by am.mirrors.kernel.org (Postfix) with ESMTPS id 5D90E1F21188
	for <lists+linux-nilfs@lfdr.de>; Sat,  2 Dec 2023 14:45:30 +0000 (UTC)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
	by smtp.subspace.kernel.org (Postfix) with ESMTP id 5F73B18C39;
	Sat,  2 Dec 2023 14:45:26 +0000 (UTC)
X-Original-To: linux-nilfs@vger.kernel.org
Received: from mail-oa1-f70.google.com (mail-oa1-f70.google.com [209.85.160.70])
	by lindbergh.monkeyblade.net (Postfix) with ESMTPS id BED83188
	for <linux-nilfs@vger.kernel.org>; Sat,  2 Dec 2023 06:45:22 -0800 (PST)
Received: by mail-oa1-f70.google.com with SMTP id 586e51a60fabf-1fafbf42404so2281565fac.1
        for <linux-nilfs@vger.kernel.org>; Sat, 02 Dec 2023 06:45:22 -0800 (PST)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1701528322; x=1702133122;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=cGD7R9zZwJRT70SwWZQhFuzSd0jIirMnne4LVz9XikI=;
        b=niU3Z2xLbCcJFjdzNsIPUjbv+1u8ocIQ2/TlWltDUD3EECCrd2HwdB9XfMHJ/IKriq
         FxX73f+7ZRrjKUrue3K4RA+jQsWfbYN5bfyi3v5stmHj5KCQ83aXAYHB3xBE3nVZeZbI
         5WN8t43tXHFVzcUkAaiTZ3d0tFv0oHHs+QVYdagSyRhi86Eih2Pq8Ga/pr8ZI9MKRqKL
         YBj/lexOlhoWGLp0BTn1R0KB84thXSaypST5a5LSXRUxgdlv6a5LDIbl/olUFPYHsj3f
         IUTWagDqE+wv/CqXX3N3a6iUR5iQUZoVqek3j4iAkog2kScJomr8iqDjH/iDWAWhcLJK
         Cimg==
X-Gm-Message-State: AOJu0YxC4uDRxLmSiDzgsnFVuKnkr2fN+gmz+yw0ALknNWnMTahg/CRo
	ynvOZhgrXyzI47xqGfCMwrxZcRdO4SXTNQkJgV5slDFeAf0J
X-Google-Smtp-Source: AGHT+IF+n1TxdK7ECbK/InLKRmAh59e9PNNRYmuRbhMaqLWrr0O7bek/khmvd3K5Ix95D/mBrYubh7cTZO9u2ytkG51dwJaAyvC4
Precedence: bulk
X-Mailing-List: linux-nilfs@vger.kernel.org
List-Id: <linux-nilfs.vger.kernel.org>
List-Subscribe: <mailto:linux-nilfs+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:linux-nilfs+unsubscribe@vger.kernel.org>
MIME-Version: 1.0
X-Received: by 2002:a05:6871:520e:b0:1fa:db12:ed96 with SMTP id
 ht14-20020a056871520e00b001fadb12ed96mr860280oac.5.1701528322005; Sat, 02 Dec
 2023 06:45:22 -0800 (PST)
Date: Sat, 02 Dec 2023 06:45:21 -0800
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <000000000000355f33060b87efe9@google.com>
Subject: [syzbot] Monthly nilfs report (Dec 2023)
From: syzbot <syzbot+listd429f3c4d04e394c92ae@syzkaller.appspotmail.com>
To: konishi.ryusuke@gmail.com, linux-fsdevel@vger.kernel.org, 
	linux-kernel@vger.kernel.org, linux-nilfs@vger.kernel.org, 
	syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"

Hello nilfs maintainers/developers,

This is a 31-day syzbot report for the nilfs subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/nilfs

During the period, 0 new issues were detected and 0 were fixed.
In total, 5 issues are still open and 36 have been fixed so far.

Some of the still happening issues:

Ref Crashes Repro Title
<1> 387     Yes   kernel BUG at fs/buffer.c:LINE!
                  https://syzkaller.appspot.com/bug?extid=cfed5b56649bddf80d6e
<2> 341     Yes   WARNING in nilfs_sufile_set_segment_usage
                  https://syzkaller.appspot.com/bug?extid=14e9f834f6ddecece094
<3> 41      Yes   kernel BUG in folio_end_writeback
                  https://syzkaller.appspot.com/bug?extid=7e5cf1d80677ec185e63
<4> 6       Yes   kernel BUG in end_buffer_async_write
                  https://syzkaller.appspot.com/bug?extid=5c04210f7c7f897c1e7f

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.

To disable reminders for individual bugs, reply with the following command:
#syz set <Ref> no-reminders

To change bug's subsystems, reply with:
#syz set <Ref> subsystems: new-subsystem

You may send multiple commands in a single email message.

