Return-Path: <linux-nilfs+bounces-154-lists+linux-nilfs=lfdr.de@vger.kernel.org>
X-Original-To: lists+linux-nilfs@lfdr.de
Delivered-To: lists+linux-nilfs@lfdr.de
Received: from sv.mirrors.kernel.org (sv.mirrors.kernel.org [139.178.88.99])
	by mail.lfdr.de (Postfix) with ESMTPS id 756D7821CD1
	for <lists+linux-nilfs@lfdr.de>; Tue,  2 Jan 2024 14:39:13 +0100 (CET)
Received: from smtp.subspace.kernel.org (wormhole.subspace.kernel.org [52.25.139.140])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by sv.mirrors.kernel.org (Postfix) with ESMTPS id 23A60284F0A
	for <lists+linux-nilfs@lfdr.de>; Tue,  2 Jan 2024 13:39:12 +0000 (UTC)
Received: from localhost.localdomain (localhost.localdomain [127.0.0.1])
	by smtp.subspace.kernel.org (Postfix) with ESMTP id A2353FC0B;
	Tue,  2 Jan 2024 13:35:18 +0000 (UTC)
X-Original-To: linux-nilfs@vger.kernel.org
Received: from mail-io1-f70.google.com (mail-io1-f70.google.com [209.85.166.70])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	by smtp.subspace.kernel.org (Postfix) with ESMTPS id 58ECEFBF5
	for <linux-nilfs@vger.kernel.org>; Tue,  2 Jan 2024 13:35:17 +0000 (UTC)
Authentication-Results: smtp.subspace.kernel.org; dmarc=fail (p=none dis=none) header.from=syzkaller.appspotmail.com
Authentication-Results: smtp.subspace.kernel.org; spf=pass smtp.mailfrom=M3KW2WVRGUFZ5GODRSRYTGD7.apphosting.bounces.google.com
Received: by mail-io1-f70.google.com with SMTP id ca18e2360f4ac-7b7fac89006so1202884839f.1
        for <linux-nilfs@vger.kernel.org>; Tue, 02 Jan 2024 05:35:17 -0800 (PST)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1704202516; x=1704807316;
        h=to:from:subject:message-id:date:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=hEPAjr2Ytd+XVdWmKta/TmOX+0CoWkrwQ31hsDPS7O8=;
        b=FUV4wi/vnkXmCs9KkEs4gJKO8vvQkYog9+FhW3pHn/j47GAtnjUqAJaC0kdoxfSc0f
         oaRhmzUfc1pYDOuPSkee4B9Fd+p2y1TabgVhrhHaykC/kHrbQzBpx2imLHO4NsWWXWzn
         GAiJsmaUwPNLKLtklkJFq6vC5IZNzRgB0aW9cxbH5jrg30nXGFN6Xi4a1nMICeZUqSk5
         iIt9UGon8MNydSUkcI6uPJjUnEBWp6eujnInGS7Hj8SF5PutmFyOKyl21Q4CwSC+WGpj
         mE3Yqj4Lf/+ixRTHnwK2q6pPWmOj5Ei2ZtBaTt7BpJMqnQyXv3eJUgiGMJ7BY6qwNxvK
         7dJg==
X-Gm-Message-State: AOJu0YwfwzDf1obieYKBEoyoqJ2u0hkj4H68VfSgRtidfrmWwZ6WiFgM
	yqTkbRKIH2NfdJAJtetbltiCzCTgQUeNdC9MF+eJayb2TFWt
X-Google-Smtp-Source: AGHT+IFgPKX0w7t+hcn0UpaleoH/hrZqqyklAqoisSpD6EBcrA4ukjJOBHKHPP89RSoNw8w3udtMT7TB3j5Fp5qCRLlrkr6yMx0U
Precedence: bulk
X-Mailing-List: linux-nilfs@vger.kernel.org
List-Id: <linux-nilfs.vger.kernel.org>
List-Subscribe: <mailto:linux-nilfs+subscribe@vger.kernel.org>
List-Unsubscribe: <mailto:linux-nilfs+unsubscribe@vger.kernel.org>
MIME-Version: 1.0
X-Received: by 2002:a05:6602:2a44:b0:7ba:9c66:6d11 with SMTP id
 k4-20020a0566022a4400b007ba9c666d11mr734766iov.1.1704202516630; Tue, 02 Jan
 2024 05:35:16 -0800 (PST)
Date: Tue, 02 Jan 2024 05:35:16 -0800
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <000000000000a11763060df691a7@google.com>
Subject: [syzbot] Monthly nilfs report (Jan 2024)
From: syzbot <syzbot+list18d7edf8faff313be6b2@syzkaller.appspotmail.com>
To: konishi.ryusuke@gmail.com, linux-fsdevel@vger.kernel.org, 
	linux-kernel@vger.kernel.org, linux-nilfs@vger.kernel.org, 
	syzkaller-bugs@googlegroups.com
Content-Type: text/plain; charset="UTF-8"

Hello nilfs maintainers/developers,

This is a 31-day syzbot report for the nilfs subsystem.
All related reports/information can be found at:
https://syzkaller.appspot.com/upstream/s/nilfs

During the period, 1 new issues were detected and 1 were fixed.
In total, 7 issues are still open and 37 have been fixed so far.

Some of the still happening issues:

Ref Crashes Repro Title
<1> 444     Yes   kernel BUG at fs/buffer.c:LINE!
                  https://syzkaller.appspot.com/bug?extid=cfed5b56649bddf80d6e
<2> 15      No    KMSAN: uninit-value in nilfs_add_checksums_on_logs (2)
                  https://syzkaller.appspot.com/bug?extid=47a017c46edb25eff048
<3> 6       Yes   kernel BUG in end_buffer_async_write
                  https://syzkaller.appspot.com/bug?extid=5c04210f7c7f897c1e7f
<4> 1       No    possible deadlock in nilfs_dirty_inode (2)
                  https://syzkaller.appspot.com/bug?extid=903350d47ddb4cbb7f6f

---
This report is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.

To disable reminders for individual bugs, reply with the following command:
#syz set <Ref> no-reminders

To change bug's subsystems, reply with:
#syz set <Ref> subsystems: new-subsystem

You may send multiple commands in a single email message.

